# Generated by Django 3.2.5 on 2021-08-12 12:00

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuators', djongo.models.fields.JSONField()),
                ('sensors', djongo.models.fields.JSONField()),
                ('metadata', djongo.models.fields.JSONField()),
                ('system', djongo.models.fields.JSONField()),
            ],
        ),
    ]
