# Generated by Django 3.2.5 on 2021-09-06 07:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
                ('metadata', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='upload',
            new_name='sensors',
        ),
        migrations.DeleteModel(
            name='example',
        ),
    ]
