# Generated by Django 3.2.5 on 2021-09-06 08:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('local_home', '0002_auto_20210906_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='growthrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField()),
                ('timestamps', djongo.models.fields.JSONField()),
            ],
        ),
    ]
